### ISSUE TITLE
upload of treatments from zookeys to BLR does not work

### ISSUE THREAD

**Issue by myrmoteras** [plazi/treatmentBank#109]
it seems that there is no upload of treatments from TB to BLR for Zookeys articles, and most likely no other Pensoft journals happening

https://zenodo.org/records/8362424 

and see https://tb.plazi.org/GgServer/summary/52AFD891F80E5925B2E26563669AFFC1

https://tb.plazi.org/GgServer/srsStats/stats?outputFields=doc.uuid+doc.articleUuid+lnk.zenodoDepId+bib.source+pubLnk.articleZenodoDepId+tax.name+tax.genusEpithet+tax.speciesEpithet&groupingFields=doc.uuid+doc.articleUuid+lnk.zenodoDepId+bib.source+pubLnk.articleZenodoDepId+tax.name&FP-tax.genusEpithet=Oreonectes%20&FP-tax.speciesEpithet=damingshanensis&format=HTML

@teodorgeorgiev

**Comment by gsautter** [comment]
Pensoft treatments are currently filtered for automated upload to Zenodo, at your specific request from a few years ago ...

The few that are up there were individually triggered manually via the server console, as a test down to the line of "please take a look whether or not this is OK" ... have yet to get a definitive answer as to whether or not that's the case.

We also might have to sort out the "intermittent treatment" issue, where Pensoft are marking intermittent non-treatment text as treatments in the TaxPub because the TaxPub DTD does not permit a normal `sec` in that position ... would be bad to put those in BLR, I guess.

**Comment by gsautter** [comment]
Here the test treatments that we uploaded ... please have a look and let me know if the depositions are OK, especially also the XHTML: https://tb.plazi.org/GgServer/srsStats/stats?outputFields=doc.uuid+doc.name+doc.uploadUser+doc.uploadDate+doc.updateUser+doc.updateDate+lnk.zenodoDepId+tax.name&groupingFields=doc.uuid+doc.name+doc.uploadUser+doc.uploadDate+doc.updateUser+doc.updateDate+lnk.zenodoDepId+tax.name&FP-doc.uploadUser=pensoft&FP-lnk.zenodoDepId=1-&format=HTML
