### ISSUE TITLE
getting Wilson, Don E. & Reeder, DeeAnn, 2005 released 

### ISSUE THREAD

**Issue by myrmoteras** [plazi/treatmentBank#116]
@gsautter can you please make sure that this catalogue is in LOD XML, GBIF, CLB, etc.? Or is there a reasons for keeping it back?
https://tb.plazi.org/GgServer/summary/1612F121776AEBF203A8EB376B6B87C6 and probably all the other other sections.

https://tb.plazi.org/GgServer/srsStats/stats?outputFields=doc.uuid+lnk.doi+lnk.gbifTaxonId+lnk.clbTaxonId+lnk.sibIlsUrl+bib.author+bib.year+tax.name+tax.rank+tax.genusEpithet+tax.speciesEpithet&groupingFields=doc.uuid+lnk.doi+lnk.gbifTaxonId+lnk.clbTaxonId+lnk.sibIlsUrl+bib.author+bib.year+tax.name+tax.rank+tax.genusEpithet+tax.speciesEpithet&FP-tax.rank=species&FP-tax.genusEpithet=Pipistrellus&FP-tax.speciesEpithet=pipistrellus&format=HTML

tx

**Comment by gsautter** [comment]
Don't think there is a reason anymore at this point ... the reason I initially blacklisted these documents for several exports was, since they are generated from a website, in anticipation of something similar happening as with InfoFlora earlier this year ... and you know as well as I do how many Zenodo DOIs we would have burned if we had exported the InfoFlora treatments right away ... it's only that in this case current case we didn't take them off the blacklist as we were busy with other things ... done now, updates going out as I type this.
