### ISSUE TITLE
species does not show up in TB search, not in Google Search

### ISSUE THREAD

**Issue by myrmoteras** [plazi/treatmentBank#16]
This is an odd case. When you search for Lepanthes microprosartima in TB or Google it does not show up. Howerver, the article is there https://tb.plazi.org/GgServer/summary/2C9516102EC55E55AC3A1E4DA795C41A as well as the treatment https://tb.plazi.org/GgServer/html/037EABB5DAE75EBDA54C12A9924F48E7

**Comment by gsautter** [comment]
Sorry, taxonomic name search finds this treatment just fine (both for full name search and for genus+species search) ... only full text search doesn't for both terms in combination, while for each individual part (genus or species), it does ... will check about the latter.

**Comment by gsautter** [comment]
After a re-index, the full text search also finds the combination of both terms ... not sure what exactly went wrong earlier, but since the XML was imported during the data sprint, the full text index might not have been updated properly for a few treatments due to the frequent restarts at the time.
