### ISSUE TITLE
file not processed  zootaxa.5062.1.1

### ISSUE THREAD

**Issue by myrmoteras** [plazi/treatmentBank#19]
@gsautter can you please check, why this file is not available. It does not show up in the transfer stats, srs etc. but when I upload it again then I get the message below

thanks
d
Donat@bern MINGW64 ~
$ cd E:/diglib/0-zootaxa/0_temp_poa_transfer3/

Donat@bern MINGW64 /e/diglib/0-zootaxa/0_temp_poa_transfer3
$ for file in *.pdf; do curl -H "....." -H "Meta-Data-Mode:Go use your templates!" -F "file=@$file; filename=$file" -F "user=plazi" -F "mimeType=application/pdf" -X PUT https://tb.plazi.org/GgServer/docUpload; done; # file
{
  "attributes": {    "docId": "6607E753652CFF81FF90FFFFFFCB5423",
    "status": "Previously imported by plazi",
    "approvalRequired": "266",
    "approvalRequired_for_document": "1",
    "approvalRequired_for_originalDoi": "1",
    "approvalRequired_for_taxonomicNames": "18",
    "approvalRequired_for_textStreams": "232",
    "approvalRequired_for_treatments": "14",
    "checkinTime": "1636374593637",
    "checkinUser": "plazi",
    "docName": "zootaxa.5062.1.1.pdf",
    "docStyle": "DocumentStyle:D239614CE4198176A422035174489AB1.1:Zootaxa.2009-2012.monograph",
    "docStyleId": "D239614CE4198176A422035174489AB1",
    "docStyleName": "Zootaxa.2009-2012.monograph",
    "docStyleVersion": "1",
    "updateTime": "1636374932061",
    "updateUser": "GgImagineBatch",
    "zenodo-license-document": "CLOSED"
  },
  "user": "plazi",
  "mimeType": "application/pdf"
}

Donat@bern MINGW64 /e/diglib/0-zootaxa/0_temp_poa_transfer3
$

**Comment by gsautter** [comment]
Well, it was uploaded and processed, but doesn't show in the article stats because it doesn't get from IMS to DIO due to some metadata problem ... the processing data stats (https://tb.plazi.org/GgServer/pdsStats) are your friend if you want to track an upload that doesn't show in the public parts of TB (we added these stats specifically for tracking documents from the moment of upload and decoding): https://tb.plazi.org/GgServer/pdsStats/stats?outputFields=doc.docUuid+doc.name+doc.uploadUser+doc.uploadDateTime+doc.updateUser+doc.updateDateTime+doc.docStyleName+docTransProbs.detailId+docTransProbs.detailLabel+docTransProbs.transSource+docTransProbs.transDest+docTransProbs.probSource+docTransProbs.probType+docTransProbs.probDescription&groupingFields=doc.docUuid+doc.name+doc.uploadUser+doc.uploadDateTime+doc.updateUser+doc.updateDateTime+doc.docStyleName+docTransProbs.detailId+docTransProbs.detailLabel+docTransProbs.transSource+docTransProbs.transDest+docTransProbs.probSource+docTransProbs.probType+docTransProbs.probDescription&FP-doc.docUuid=6607E753652CFF81FF90FFFFFFCB5423&format=HTML

**Comment by myrmoteras** [comment]
@gsautter thanks - I fixed the metadata and it is there - 128 more treatments in TB

Also thanks for  (https://tb.plazi.org/GgServer/pdsStats)  wasn't aware of this tool.
