### ISSUE TITLE
twice authority name and authoriry

### ISSUE THREAD

**Issue by myrmoteras** [plazi/treatmentBank#50]
@gsautter in this case, both the authority name and authority are showing up. I can't fix it, and I also buffled why this occurs in two articles
![image](https://user-images.githubusercontent.com/4609956/167107919-19dd5ee0-68f3-4173-9b43-9c82cd019bfa.png)

https://tb.plazi.org/GgServer/html/CF87EFC9FF6A594CA0FCB2CD2ED36A72

https://tb.plazi.org/GgServer/html/D82E8784FFD579722ADAFE17FBCBD327?cacheControl=force

2417FFFCFFD179772A69FFEEFFCAD673
FFC8FFF7FF8EFFFE9F6EFFEEFFFF3860

**Comment by flsimoes** [comment]
The issue is caused by the author name being part of the taxonomicName. Splitting it solves the problem, which does occur throughout the text.

Fix for S. agnoston as an example:
![image](https://user-images.githubusercontent.com/3343086/167126209-606ccc8a-4a32-49a9-8f3c-39715cebead4.png)
![image](https://user-images.githubusercontent.com/3343086/167126687-1fd40fc2-5125-4651-8076-a6c95e32aa27.png)

![image](https://user-images.githubusercontent.com/3343086/167126229-8944d4dd-7980-4348-a2e1-94416c90e7d5.png)
![image](https://user-images.githubusercontent.com/3343086/167126775-492797f6-0a5a-4bf4-b929-b8887887886b.png)

**Comment by gsautter** [comment]
This might simply be a rendering issue ... will look into the XSLT that produces the treatment pages.

**Comment by gsautter** [comment]
> This might simply be a rendering issue ... will look into the XSLT that produces the treatment pages.

That said, no need to split authorities off names ... they _should_ be included.

**Comment by gsautter** [comment]
Turns out the XSLT is actually fine ... it actually does check if the taxon name string contains the authority, and if so, doesn't add it ... only in this treatment, it's `S.Knapp` in the text vs. `S. Knapp` in the attribute, so this was as simple as a spacing issue ... if you look closely, you can even see that in the screenshot above.

Still have to add the year, though, as that isn't given in the text, so I'll need to adjust the XSLT after all ...

**Comment by gsautter** [comment]
Changed the XSLT now so it also adds the year from the `authorityYear` attribute if it isn't given in the text.
