### ISSUE TITLE
upload of megataxa.8.1.1 to frankfurt fails

### ISSUE THREAD

**Issue by myrmoteras** [plazi/treatmentBank#75]
@gsautter can you please have a look at this file and why it does not upload? the file is [here](https://mapress.com/mt/article/view/megataxa.8.1.1) - may be it id due to the size (900MB)? 

> $ for file in *.pdf; do curl -H "Authorization:How can there be a copyright on stating that the sky is blue?" -H "Meta-Data-Mode:Go use your templates!" -F "file=@$file; filename=$file" -F "user=plazi" -F "mimeType=application/pdf" -X PUT https://tb.plazi.org/GgServer/docUpload; done; # file
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>502 Bad Gateway</title>
</head><body>
<h1>Bad Gateway</h1>
<p>The proxy server received an invalid
response from an upstream server.<br />
</p>
</body></html>

**Comment by gsautter** [comment]
Not sure what might have caused the error, but file size might have played a role with this behemoth ... anyway, downloaded it to the server now, and triggered the import via local file intake ... the PDF is decoding as I type this.

**Comment by gsautter** [comment]
Looks like decoding proper went well, but when the decoder stored the resulting IMF on the RAM disk for the main server to pick it up, it ran out of disk space (on that specific 8GB RAM disk, which is otherwise empty, as we use it solely for disk based file handover between components in the main server and their sub processes, i.e., PDF decoding and server side batch) ... need to increase the size of the RAM disk and try again ...

**Comment by myrmoteras** [comment]
thanks . looks good
